import {useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {appSettings,db} from '../../data/db'
import {goalRepo,preferencesRepo,profileRepo} from '../../data/repositories'
import type {GoalType,UserPreferences} from '../../domain/models'
import {Button,Card} from '../../components/UI'
const labels:Record<GoalType,string>={muscle:'بناء العضلات',fat_loss:'خسارة الدهون',recomp:'إعادة تكوين الجسم',strength:'زيادة القوة',fitness:'تحسين اللياقة',maintain:'الحفاظ على الوزن'}
const days=['السبت','الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة']
export default function OnboardingPage(){
 const nav=useNavigate();const[step,setStep]=useState(0);const[name,setName]=useState('');const[birthYear,setBirthYear]=useState(2000);const[height,setHeight]=useState(175);const[weight,setWeight]=useState(75);const[goal,setGoal]=useState<GoalType>('muscle');const[workoutDays,setWorkoutDays]=useState<string[]>(['السبت','الاثنين','الأربعاء']);const[equipment,setEquipment]=useState<string[]>(['دمبل','بار']);const[place,setPlace]=useState<UserPreferences['trainingPlace']>('gym')
 const toggle=(v:string,list:string[],set:(x:string[])=>void)=>set(list.includes(v)?list.filter(x=>x!==v):[...list,v])
 async function finish(){const userId=crypto.randomUUID();await db.users.add({id:userId,createdAt:new Date().toISOString()});await profileRepo.save({userId,name:name.trim(),birthYear,heightCm:height,currentWeightKg:weight,experience:'beginner',activityLevel:'moderate'});await goalRepo.save({userId,primary:goal,pace:'moderate',priority:1,targetWeightKg:weight});await preferencesRepo.save({userId,workoutDays,restDays:days.filter(d=>!workoutDays.includes(d)),equipment,trainingPlace:place,workoutDurationMin:60,preferredWorkoutTime:'18:00',supplementsEnabled:[],foodPreferences:[],dislikedFoods:[],cookingTimeMin:30,budgetLevel:'medium'});appSettings.activeUserId=userId;appSettings.onboardingCompleted=true;nav('/',{replace:true})}
 return <div className="onboarding"><div className="onboarding-panel"><div className="logo-mark">G</div><div className="step-dots">{[0,1,2,3].map(i=><span key={i} className={i<=step?'active':''}/>)}</div>
 {step===0&&<><h1>مساعدك اليومي للجيم ونمط الحياة</h1><p>بياناتك تظل على جهازك، والتطبيق يتكيف مع هدفك وتفضيلاتك.</p><Button onClick={()=>setStep(1)}>ابدأ الآن</Button></>}
 {step===1&&<Card title="بياناتك الأساسية"><label>الاسم<input value={name} onChange={e=>setName(e.target.value)} placeholder="اكتب اسمك"/></label><label>سنة الميلاد<input type="number" value={birthYear} onChange={e=>setBirthYear(Number(e.target.value))}/></label><label>الطول (سم)<input type="number" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><label>الوزن الحالي (كجم)<input type="number" value={weight} onChange={e=>setWeight(Number(e.target.value))}/></label><Button disabled={!name.trim()} onClick={()=>setStep(2)}>التالي</Button></Card>}
 {step===2&&<Card title="ما هدفك الأساسي؟"><div className="option-grid">{Object.entries(labels).map(([k,v])=><button key={k} className={`choice ${goal===k?'selected':''}`} onClick={()=>setGoal(k as GoalType)}>{v}</button>)}</div><Button onClick={()=>setStep(3)}>التالي</Button></Card>}
 {step===3&&<Card title="كيف تحب أن تتمرن؟"><h3>أيام التمرين</h3><div className="chips">{days.map(d=><button key={d} className={workoutDays.includes(d)?'chip active':'chip'} onClick={()=>toggle(d,workoutDays,setWorkoutDays)}>{d}</button>)}</div><h3>المعدات</h3><div className="chips">{['دمبل','بار','كابل','أجهزة','وزن الجسم'].map(d=><button key={d} className={equipment.includes(d)?'chip active':'chip'} onClick={()=>toggle(d,equipment,setEquipment)}>{d}</button>)}</div><h3>مكان التدريب</h3><div className="chips"><button className={place==='gym'?'chip active':'chip'} onClick={()=>setPlace('gym')}>الجيم</button><button className={place==='home'?'chip active':'chip'} onClick={()=>setPlace('home')}>البيت</button><button className={place==='both'?'chip active':'chip'} onClick={()=>setPlace('both')}>الاثنان</button></div><Button disabled={!workoutDays.length} onClick={finish}>إنهاء الإعداد</Button></Card>}
 </div></div>
}
