import {useState} from 'react'
import {useLiveQuery} from 'dexie-react-hooks'
import {appSettings} from '../../data/db'
import {recoveryRepo} from '../../data/repositories'
import {Button,Card,EmptyState,Page,Stat} from '../../components/UI'
export default function RecoveryPage(){const userId=appSettings.activeUserId!;const logs=useLiveQuery(()=>recoveryRepo.list(userId),[userId])??[];const[sleepHours,setSleepHours]=useState(7);const[sleepQuality,setSleepQuality]=useState(7);const[fatigue,setFatigue]=useState(4);const[soreness,setSoreness]=useState(4);const[pain,setPain]=useState(0);async function save(){await recoveryRepo.add({userId,date:new Date().toISOString(),sleepHours,sleepQuality,fatigue,soreness,pain})}const latest=logs[0];const score=latest?Math.round(Math.max(0,Math.min(100,Math.min(100,latest.sleepHours/8*100)*.35+latest.sleepQuality*10*.15+(10-latest.fatigue)*10*.2+(10-latest.soreness)*10*.15+(10-latest.pain)*10*.15))):null;const decision=score==null?'سجّل بياناتك أولاً':score>=75?'تمرن طبيعيًا':score>=55?'تمرن بخفة وقلل الحجم':'اجعل اليوم للتعافي';return <Page title="الجاهزية والتعافي" subtitle="قرار واضح ومفسر، بدون عشوائية"><Card title="تسجيل حالتك"><div className="form-grid"><label>ساعات النوم<input type="number" onFocus={(event) => event.currentTarget.select()} step=".5" value={sleepHours} onChange={e=>setSleepHours(Number(e.target.value))}/></label><label>جودة النوم 1-10<input type="range" min="1" max="10" value={sleepQuality} onChange={e=>setSleepQuality(Number(e.target.value))}/><span>{sleepQuality}</span></label>
<label>الإجهاد 1-10<input type="range" min="1" max="10" value={fatigue} onChange={e=>setFatigue(Number(e.target.value))}/><span>{fatigue}</span></label>
<label>ألم العضلات 1-10<input type="range" min="1" max="10" value={soreness} onChange={e=>setSoreness(Number(e.target.value))}/><span>{soreness}</span></label>
<label>الألم 0-10<input type="range" min="0" max="10" value={pain} onChange={e=>setPain(Number(e.target.value))}/><span>{pain}</span></label></div><Button onClick={save}>حفظ الحالة</Button></Card><Card title="قرار اليوم"><div className="stats-grid"><Stat label="الجاهزية" value={score==null?'—':`${score}%`}/><Stat label="القرار" value={decision}/></div><p className="muted">النتيجة تعتمد على النوم وجودته والإجهاد وألم العضلات والألم المسجل.</p></Card><Card title="آخر السجلات">{logs.length?<div className="list">{logs.slice(0,7).map(l=><div className="list-row" key={l.id}><span>{new Date(l.date).toLocaleDateString('ar-EG')}</span><strong>{l.sleepHours} س نوم</strong><span>إجهاد {l.fatigue}/10</span></div>)}</div>:<EmptyState text="لا توجد سجلات تعافٍ بعد"/>}</Card></Page>}
